log.config.path=../logs/muse-back-service
log.config.app.error.name=muse_back_service_test_app_error
log.config.app.warn.name=muse_back_service_test_app_warn
log.config.sql.error.name=muse_back_service_test_sql_error
log.config.sql.trace.name=muse_back_service_test_sql_trace
